BEGIN;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO bot;
GRANT INSERT, UPDATE, DELETE ON appointment_services TO bot;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO bot;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO bot;

ALTER DEFAULT PRIVILEGES FOR ROLE salon IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE ON TABLES TO bot;
ALTER DEFAULT PRIVILEGES FOR ROLE salon IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO bot;
ALTER DEFAULT PRIVILEGES FOR ROLE salon IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO bot;

REVOKE INSERT, UPDATE, DELETE ON appointments_history FROM bot;

COMMIT;
